name: Automatic Release

on:
  push:
    branches:
      - development

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for differences
        id: diff-check
        run: |
          git diff --quiet origin/main...HEAD || echo "has_changes=true" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge development into main"
          branch: development
          base: main
          title: "Automatic PR: Merge development into main"
          body: |
            This PR is automatically created to merge the latest changes from `development` into `main`.
          labels: ["automatic-release"]